#!/nix/store/x7fr0bvnwvqvr3zg60di9jxvfwimcw7m-bash-4.4-p23/bin/sh

sxhkd &
#xrandr --newmode "2560x1440_60.00"  311.83  2560 2744 3024 3488  1440 1441 1444 1490  -HSync +Vsync
#xrandr --addmode Virtual1 2560x1440_60.00
#xrandr --output Virtual1 --mode 2560x1440_60.00

~/.config/polybar/launch.sh
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
